server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: driver
          uri: http://localhost:8081
          predicates:
            - Path=/drives/**, 
        - id: indexer
          uri: http://localhost:8082
          predicates:
            - Path=/indices/**, 
        - id: video processing
          uri: http://localhost:8083
          predicates:
            - Path=/streams/**, 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path=, /dashboards/**
        - id: notification
          uri: http://localhost:8085
          predicates:
            - Path=/nofities/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: driver
          uri: http://driver:8080
          predicates:
            - Path=/drives/**, 
        - id: indexer
          uri: http://indexer:8080
          predicates:
            - Path=/indices/**, 
        - id: video processing
          uri: http://videoProcessing:8080
          predicates:
            - Path=/streams/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /dashboards/**
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/nofities/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
